steps:

# Simple sanity check: invoke the new gcloud container to confirm that it was
# built correctly.
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute' , 'scp' , 'cicd-pipeline-train-schedule-git/' , 'khushaboo_khudia@instance-3:/home/khushaboo_khudia' , '--recurse' , '--zone=us-central1-a']

timeout: 1200s
