steps:

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
  - '-c'
  -  |
      for d in routes/*; do
              gcloud compute scp $d khushaboo_khudia@10.128.15.232:/home/khushaboo_khudia/demo --zone=us-central1-a --recurse
      done
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute' , 'ssh', 'khushaboo_khudia@10.128.15.232' , '--zone=us-central1-a' , '--command="ls"']      

timeout: 1200s



#- name: 'gcr.io/cloud-builders/gcloud'
#  entrypoint: 'bash'
#  args: 
#  - '-c'
#  -  |
#      for d in *; do
#              if [ -d routes ]
#              then
#                  gcloud compute scp $d pranay_nanda@instance-2:/home/pranay_nanda/demo --zone=us-central1-a --recurse
#              else
#                  gcloud compute scp $d pranay_nanda@instance-2:/home/pranay_nanda/new --zone=us-central1-a --recurse
#                  fi
#      done
